### ISSUE TITLE
Research Database Backup

### ISSUE THREAD

**Issue by AndrewPyscher** [adamuremek/mentorship-program#111]

**Comment by goupil-justin** [comment]
Created a script that can be used to backup the database.
https://github.com/adamuremek/mentorship-program/commit/a002b36a294bc8b462070357803c83571febba5f

Made using https://www.postgresql.org/docs/current/backup-dump.html

Need to implement a restore script now.

**Comment by goupil-justin** [comment]
Created a script that can be used to restore the database from the .sql.tar.gz file.
https://github.com/adamuremek/mentorship-program/commit/3cdd0ec205a57f551a1460360944ccbf25fbd0ef

**Comment by goupil-justin** [comment]
Created two scripts that can be used to create a backup of the media directory and restore it.
https://github.com/adamuremek/mentorship-program/commit/56dd1ec9e79e04937bd655cd9f7cbbd4a4591643

**Comment by goupil-justin** [comment]
Added a way to limit the number of active backups in settings.py using BACKUP_DATABASE_COUNT. Scripts will maintain this number and remove old files.

https://github.com/adamuremek/mentorship-program/commit/8675cacb216dabb83b9938e55816522e115bc0f0
