### ISSUE TITLE
Can request the same mentor more than once after they accept.

### ISSUE THREAD

**Issue by atunutu** [adamuremek/mentorship-program#163]
Student requests mentor
mentor accepts
student requests same mentor again (from dashboard) and the request shows up in mentor account

**Comment by mdloucks** [comment]
Duplicated issue. Going to add safeguard in backend_requests.py -> request_mentor.

<img width="934" alt="Screenshot 2024-04-09 at 12 33 54 PM" src="https://github.com/adamuremek/mentorship-program/assets/19471665/6fbe385c-8154-4079-a10e-191e7c08ff49">
