### ISSUE TITLE
Admin Mentorship Creation Clears Mentee List

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#164]
On the User Management page:
1. Click on the plus button next to a mentee.
2. Click on the button to display the mentees related to a mentor.
The mentorship is created, but the list of mentees appears without the new addition showing.
This also applies to other mentor operations like disabling their account or decoupling from the organization.
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/16355841-0554-42e3-a414-445ce4c6dfdb)

**Comment by AndrewPyscher** [comment]
We've determined this isn't a bug
