### ISSUE TITLE
Settings side bar kinda off on mobile screens, hard to distinguish menu options from background, especially the exit button

### ISSUE THREAD

**Issue by atunutu** [adamuremek/mentorship-program#175]
![BF4D93C4-BFD9-42F6-8537-AE297288490F](https://github.com/adamuremek/mentorship-program/assets/83090752/2e7addd7-4520-4f1b-b581-e611f8e72356)

**Comment by kotht** [comment]
Something with the css blur() function. Will fix shortly.

**Comment by kotht** [comment]
Should be fixed, tested on a iPhone emulator with the result being shown below.
![Screenshot 2024-04-10 113946](https://github.com/adamuremek/mentorship-program/assets/108773436/5a04a3fb-399c-41a5-9c43-12a298ac7b4b)
