### ISSUE TITLE
Can't view mentee page

### ISSUE THREAD

**Issue by mdloucks** [adamuremek/mentorship-program#184]
On https://mentorship-program-prod.jordananodjo.com/universal_profile/7

This error was thrown after updating bio to the following

```
 <script>alert("HACKED")</script> <img src="javascript:alert(`XSS`)> <img src="javascript:alert(&quot;XSS&quot;)> <a href="javascript:alert(`XSS`)">My Profile</a>
```

<img width="1164" alt="Screenshot 2024-04-11 at 6 36 15 PM" src="https://github.com/adamuremek/mentorship-program/assets/19471665/df9b9d20-909a-437a-a6c2-fdc39c468918">

**Comment by mdloucks** [comment]
Seems like an edge case though. Viewing blank profile works.

**Comment by nick16hood** [comment]
I also got the same issue when trying to view my men
![Capture](https://github.com/adamuremek/mentorship-program/assets/108694683/af1e8da3-a3ce-4eae-b1c5-20e6d9c14394)
tee page.

**Comment by mdloucks** [comment]
<3 https://github.com/adamuremek/mentorship-program/issues/190
