### ISSUE TITLE
Organization Dropdown Extra blank option

### ISSUE THREAD

**Issue by nick16hood** [adamuremek/mentorship-program#188]
![Screenshot 2024-04-11 184239](https://github.com/adamuremek/mentorship-program/assets/108694683/d855fe43-9290-41bb-8467-99695c7a6dc4)

No need for extra blank option. Can select the top for not selecting an organization

**Comment by goupil-justin** [comment]
Discovered that the blank space was added to the organization database. Attempting to figure out how it got added.

**Comment by goupil-justin** [comment]
Possible Cause: 

I observed that when a new mentor is created the blank entry is also added to the database. Creating an organization as an admin did not introduce the blank space.
