### ISSUE TITLE
Profile editing

### ISSUE THREAD

**Issue by Punkster81** [adamuremek/mentorship-program#189]
When editting, first name, last name, job title, and phone they are glaring white boxes

**Comment by Punkster81** [comment]
and the experience drop down is squished

**Comment by Punkster81** [comment]
and the pronouns

**Comment by Punkster81** [comment]
if no pronouns theres still the / like "he/him" but its just " / "

**Comment by AndrewPyscher** [comment]
Fake issue
its behind

**Comment by Punkster81** [comment]
thanks pookie
