### ISSUE TITLE
Attempting to view a mentee page that requested mentor

### ISSUE THREAD

**Issue by gabefoor** [adamuremek/mentorship-program#190]
I sent a request to a mentor. I signed in as the requested mentor and I attempted to view the profile of the mentee account that sent the request and got this error. 
![MentorAttemptToViewMentee](https://github.com/adamuremek/mentorship-program/assets/65245642/604dfe1e-88b3-42d4-8787-d870dd861590)

**Comment by AndrewPyscher** [comment]
99.99% sure this was just because of the issue we had when deploying. Cannot replicate
