### ISSUE TITLE
Tab name for profiles is ¯\_(Profile)_/¯

### ISSUE THREAD

**Issue by goupil-justin** [adamuremek/mentorship-program#191]
![image](https://github.com/adamuremek/mentorship-program/assets/142522764/6e67debc-ccb2-43e9-9608-1d84a1d9362d)

**Comment by calebhunt5** [comment]
Changed tab title to say "FIRSTNAME's Profile" for mentee's profiles and "FIRSTNAME's Group" for mentors:
![image](https://github.com/adamuremek/mentorship-program/assets/64340885/becc3767-faab-41ec-9c93-8d2c657b8d53)
![image](https://github.com/adamuremek/mentorship-program/assets/64340885/5462bddf-d887-476a-85c8-7d0bf9ba650e)
