### ISSUE TITLE
Reporting broken

### ISSUE THREAD

**Issue by mdloucks** [adamuremek/mentorship-program#193]
https://mentorship-program-prod.jordananodjo.com/save_profile_info/21

We will probably never see this type of input, but it would be nice to handle it and redirect to like a 400 err. Potentially related to https://github.com/adamuremek/mentorship-program/issues/184

When inserting the following bs

EDIT: It throws this error with any input

```
 <script>alert("HACKED")</script> <img src="javascript:alert(`XSS`)> <img src="javascript:alert(&quot;XSS&quot;)> <a href="javascript:alert(`XSS`)">My Profile</a>
```

<img width="929" alt="Screenshot 2024-04-11 at 6 50 32 PM" src="https://github.com/adamuremek/mentorship-program/assets/19471665/367217f5-e4ed-4c06-b5ff-fa8fd8a4597a">

You will receive the following error

<img width="1208" alt="Screenshot 2024-04-11 at 6 51 15 PM" src="https://github.com/adamuremek/mentorship-program/assets/19471665/78cf2e30-c4e4-4323-8d53-790957818170">

**Comment by AndrewPyscher** [comment]
99.99% sure this was just because of the issue we had when deploying. Cannot replicate
