### ISSUE TITLE
Mentor sign-in returns 400 Bad Request if you have signed in from another device.

### ISSUE THREAD

**Issue by goupil-justin** [adamuremek/mentorship-program#206]
As a mentor you cannot sign into an account if you have signed in from another device. Can still login using the device you first signed into.
Steps to reproduce
1. Sign into a mentor account on one device.
2. Sign out of the mentor account.
3. Attempt to sign into a mentor account from a different device.
4. Redirected to 400 Bad Request.

**Comment by goupil-justin** [comment]
Verified, still an issue.

**Comment by goupil-justin** [comment]
The database was wiped yesterday so I checked this again.

It appears the database wipe has resolved whatever caused the 400 error.

Still not sure what the cause was. Should mark this as closed if no one else can reproduce it.

**Comment by calebhunt5** [comment]
I was also able to login on both my laptop and my phone today, it looks like the database wipe resolved this issue
