### ISSUE TITLE
Mentor Creation Application Removes Organization

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#219]
When a mentor applies for an account, the application shows them as having no organization. If approved, their profile also does not have an organization. They are put in a group in user management for an organization with no name.
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/b20e09cc-43f6-4c0b-90f8-a861c83c4203)
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/3f0a9842-c8c5-48da-822e-025ed84ec55a)

**Comment by sajohn10** [comment]
It looks like it is happening again
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/0d4421c8-37f7-47a7-878e-4b3d9096ba7a)

**Comment by sajohn10** [comment]
Now when trying to apply this happens after choosing mentor
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/1e5cfacf-520c-4b4e-b6bf-0a6b2b0d5775)
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/0ffeb0bc-38cb-403c-9589-c5874b0c3463)

**Comment by AndrewPyscher** [comment]
Both of these should be fixed now. Test again and close if it is
