### ISSUE TITLE
Two Blank Options for Company in Application & Misspelling in Interests

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#225]
When applying to be a mentor, there are 2 options for a blank company.
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/436ce28f-7a51-47b0-9bef-5f4395b6dda6)

Also, Distributed Systems has a typo in the interests
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/656b2472-4746-423f-a1df-73c03dc5d643)

**Comment by goupil-justin** [comment]
The other option allows you to enter a blank space.
![image](https://github.com/adamuremek/mentorship-program/assets/142522764/d5db8932-5e15-482b-aff3-d3d4d6c2fb12)

![image](https://github.com/adamuremek/mentorship-program/assets/142522764/8767ad3f-2524-4046-9792-b8f8e66723cf)


Reproduction steps:

As a new user:
1. Create a mentor account as normal until step 3.
2. In the company drop down select 'Other' 
3. In the text box that appears selected it and press space to input " "
4. Continue as normal to the end.

As an Admin:
1. Approve the new mentor account.
2. Logout

As a new mentor:
1. Follow the creation process to step 3.
2. Select company and observe that " " is now an option.

**Comment by goupil-justin** [comment]
https://github.com/adamuremek/mentorship-program/commit/b8132131c764d40affcb9d5cb1def08d4bb1344f

**Comment by sajohn10** [comment]
I was able to enter an application with a space
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/1ae762ea-a105-440c-86d9-db2aaa0dd590)

**Comment by sajohn10** [comment]
Also the application still shows the typo in interests

**Comment by goupil-justin** [comment]
@sajohn10 Could you explain the process you took to add the blank space?

Typo is fixed, I don't understand. https://github.com/adamuremek/mentorship-program/commit/f264c6ae746eb4ccbe6a38e1f52df4b00bbb851d

![image](https://github.com/adamuremek/mentorship-program/assets/142522764/61ddb57a-742e-42f0-9727-bc2dd0cd3f35)

**Comment by sajohn10** [comment]
idk what happened in the last half hour but it got fixed, sorry about that

**Comment by goupil-justin** [comment]
@sajohn10 It's all good man.
