### ISSUE TITLE
Changing Profile Pic Creates Empty Space

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#227]
Both mentors and mentees updating profile pictures removes any image.
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/c68cc801-f514-4e97-bebc-34bcc8b3d6c8)

**Comment by goupil-justin** [comment]
Currently working on a local database:
![image](https://github.com/adamuremek/mentorship-program/assets/142522764/5713cf0f-b929-4b67-8668-a771e1df8d43)

Waiting for the production server to start backup to check on there.

**Comment by goupil-justin** [comment]
Working on production server.
![image](https://github.com/adamuremek/mentorship-program/assets/142522764/8dd3e881-be31-4a41-890f-28cd7940f1a6)
