### ISSUE TITLE
There's a blank option when editing pronouns, not sure if intentional 

### ISSUE THREAD

**Issue by atunutu** [adamuremek/mentorship-program#228]
![image](https://github.com/adamuremek/mentorship-program/assets/83090752/3585ac72-db2e-4183-9a36-953a82d66d57)

also I remember Eric LaVoie say the options need to be more inclusive, not sure if he meant more options or an option for not displaying them at all

**Comment by AndrewPyscher** [comment]
Yes its intentional

**Comment by goupil-justin** [comment]
Last I was heard the blank space is intentional in case the user did not want pronouns listed. I'll drop this on discord and ask what they would like done. Imo, 'they' is kind of a catch all pronoun if one is missing and they could always add it to their bio.

ah- Just as I was about to comment
