### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by goupil-justin** [adamuremek/mentorship-program#230]
When a user replaces their profile image with another it creates an orphaned image that remains in the media/images folder. 

![image](https://github.com/adamuremek/mentorship-program/assets/142522764/204142a5-8481-41fd-9e80-3694dabaced1)

**Comment by goupil-justin** [comment]
Fixed I think: https://github.com/adamuremek/mentorship-program/commit/e2ce147151a4092ab17da7051545b8d27729b209

![image](https://github.com/adamuremek/mentorship-program/assets/142522764/f5377129-d835-4343-b732-e7d7cdad86e1)

![image](https://github.com/adamuremek/mentorship-program/assets/142522764/c1861dd8-2a1d-46d9-bd9e-ec8a705f2f6e)

**Comment by TheSlimyOne** [comment]
Were you able to finish this task? @goupil-justin

**Comment by goupil-justin** [comment]
Yes. @TheSlimyOne  

Sorry, I should have asked that if someone has the time could you please verify that the fix worked.

**Comment by TheSlimyOne** [comment]
The code you pushed took down the server for some reason

**Comment by goupil-justin** [comment]
Oh shit, are there any logs?

**Comment by goupil-justin** [comment]
link to the commit: https://github.com/adamuremek/mentorship-program/commit/e2ce147151a4092ab17da7051545b8d27729b209

**Comment by TheSlimyOne** [comment]
It might be a server issue quinn was fixing somethings i'll let you know if I learn anything

**Comment by goupil-justin** [comment]
Roger, I'll try to stay on til 12.

**Comment by goupil-justin** [comment]
@TheSlimyOne Looks like every check has been failing since 1:40pm today.
