### ISSUE TITLE
Unapproved Mentors in User Management

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#231]
Mentors waiting for their application to be approved appear in User Management, and can have mentorships created.
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/6ec2903e-f17e-439a-a783-c940fd50c549)
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/cf3c50af-5393-4071-8ef9-af413aa3df55)

**Comment by AndrewPyscher** [comment]
To whoever is going to fix this, make sure the solution doesn't drastically slow down the loading of the page.

**Comment by goupil-justin** [comment]
https://github.com/adamuremek/mentorship-program/issues/231 This should do it.

**Comment by goupil-justin** [comment]
Mentors with the MENTOR_PENDING role no longer show up in the user management screen.

https://github.com/adamuremek/mentorship-program/commit/c81658995d67699d6ebdbd06db476d6adee03f5e
