### ISSUE TITLE
User Management Search Shows Decoupled Mentors

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#232]
Searching by company in User Management  shows mentors not tied to an organization. Also, searching by name then searching by company clears the search by name for mentors.
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/4c7c5f52-2936-4bbf-94ac-84a44043d57e)

**Comment by TheSlimyOne** [comment]
iirc you cannot search organization and users at the same time so thats why it clears. @anthonyPeters143 was that intended?

**Comment by mdloucks** [comment]
@TheSlimyOne I think it's because it doesn't filter the top mentors. See attached video

Uploading Screen Recording 2024-04-18 at 10.28.16 AM.mov…

**Comment by anthonyPeters143** [comment]
@mdloucks the filtering was setup to override each other, so users within organizations weren't being filtered when filtering users. I'm a little confused on what is fixed and what is the bug? If you can hit me up in person after class or on discord and look at it with you or get back to you.

Thank you, I'm glad it makes sense to others.

**Comment by mdloucks** [comment]
Yeah sounds good I'll hunt you down after Dr. James is done yapping
