### ISSUE TITLE
Empty options in Company options 

### ISSUE THREAD

**Issue by atunutu** [adamuremek/mentorship-program#239]
![image](https://github.com/adamuremek/mentorship-program/assets/83090752/ebc8084a-b5bc-4e1d-9180-44ac2f2e78b6)

**Comment by atunutu** [comment]
also these could be aligned better
definitely more spacing between company type and experience textboxes 
![image](https://github.com/adamuremek/mentorship-program/assets/83090752/ee797728-97ec-4346-9b59-df7263bf06e3)

**Comment by goupil-justin** [comment]
Manually removed all empty name organizations as an admin. If you find a new way to create an organization with out a name, please document your steps.
