### ISSUE TITLE
User Settings Page - Password Change - Allows same password

### ISSUE THREAD

**Issue by syrin1cr** [adamuremek/mentorship-program#254]
Lets you change the accounts password with the same password you currently have set.

![image](https://github.com/adamuremek/mentorship-program/assets/18075615/f4643f3d-2ecd-4843-8716-9496cdc007f6)

**Comment by syrin1cr** [comment]
Same issue with account recovery function.

![image](https://github.com/adamuremek/mentorship-program/assets/18075615/8f63ecd6-266b-40bd-afff-acb6eadcea07)

**Comment by AndrewPyscher** [comment]
Not a bug
