### ISSUE TITLE
Reported Users Missing Back Button

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#258]
There's no back button when relooking at reports
![image](https://github.com/adamuremek/mentorship-program/assets/148512356/9b7740a0-a863-4acd-9765-21ca1d97d453)

**Comment by goupil-justin** [comment]
Here ya gooo

![image](https://github.com/adamuremek/mentorship-program/assets/142522764/fc31402d-ad12-4e3f-a8f3-21002d8214b1)
