### ISSUE TITLE
When a mentor sends a request to a mentee from their profile, if they go back to the dashboard the "Request Mentee" button for the mentee they requested is now "Decline Request" and not "Cancel Request"

### ISSUE THREAD

**Issue by atunutu** [adamuremek/mentorship-program#260]
Steps to recreate error:
request a mentee from their profile
go back to dashboard and refresh
the mentee requested has "Decline Request" button instead of "Cancel Request"

**Comment by AndrewPyscher** [comment]
This is a lost cause.
