### ISSUE TITLE
Superadmin Creation and Login

### ISSUE THREAD

**Issue by adamuremek** [adamuremek/mentorship-program#31]
# Description

As of right now, we need to have a way to create at least one super admin. This should be done with using internal configuration via the .env file or a separate text/storage file. The super admin credentials (username, password, email) should be loaded from the file into the login system to use the credentials for validation. Ideally, the best workflow for implementing this feature that i can think of is to create a command line utility that you can use to set up the admin creds and produce the cred file, ideally with encrypted information. That way the password can be hashed instead of being stored in plaintext.

**Comment by goupil-justin** [comment]
Added under [feat/mentor_accepting](https://github.com/adamuremek/mentorship-program/tree/feat/mentor_accepting). 
[Link to commit](https://github.com/adamuremek/mentorship-program/commit/a14a97afe2af6f016420b91ec17c9c3fcdc56a23)

[Django docs](https://docs.djangoproject.com/en/5.0/howto/custom-management-commands/#module-django.core.management)
[Geek for Geeks article](https://www.geeksforgeeks.org/custom-django-management-commands/)

Closing.
