### ISSUE TITLE
Profile Picture Storage and Retrieval

### ISSUE THREAD

**Issue by adamuremek** [adamuremek/mentorship-program#38]
# Description

Uploaded profile pictures will be sent to a route, which will id the image, key the image in the db, then store the image in a storage directory. The project will need to know where this storage directory is located ahead of time via the env or some other configuration. The image id should be tied to the user, so when their profile is loaded, their pic will be loaded along with it.

**Comment by isaiahgalaviz07** [comment]
Made a route called "update_profile_img" within the 'under_development' file to update images for user profiles (passes in a POST request that will contain the file "name"). 
At the moment, some testing is needed to ensure that profile images save properly and can be retrieved on any client device running the program. I was also debating on what the passed in string should look like (should it be a directory path or just the name of the file?).

Also made a class in the 'models.py' file called "ProfileImg", where instances can be created to keep track of profile images associated with each user.
