### ISSUE TITLE
BUG: Sign up from the "+" button [Mentee and Mentor Sign-Up]

### ISSUE THREAD

**Issue by gmai2015gm** [adamuremek/mentorship-program#46]
_**DESCRIPTION**_
The "+" button on the interest selection page submits the registration form before prompting for the user agreement.

_**Steps to reproduce**_

1. Go through the registration form (for either mentee or mentor) and fill in testing information.
2. When prompted for interests, press the "+" button with 0 or more interests selected. 
3. The page will submit the form and will provide either a confirmation or a reason for denial.

_**Additional Comments**_
- Opera GX was used for testing
- Please contact for any questions or demo

**Comment by AndrewPyscher** [comment]
I removed the "+" from the signup page. This will effect both mentors and mentees. The ability to add new interests will go to the admin page so that there is control over what the interests are, and to avoid repetitive ones
