### ISSUE TITLE
Metric That Shows Qantity of Mentees that have Mentors

### ISSUE THREAD

**Issue by adamuremek** [adamuremek/mentorship-program#59]
# Description

This metric can either be a number or percentage. It doesn't matter as long as it shows how many registered mentees have a mentor and how many don't. Functionality should be implemented inthe report and on the admin dashboard if possible.

**Comment by TheSlimyOne** [comment]
https://github.com/adamuremek/mentorship-program/commit/592c360459a2241ab6427bbb94eaaa4a602ec391
Fixed

**Comment by TheSlimyOne** [comment]
CSS doesnt show up 
Need to replace A with another statistic or remove the statisic entirely
