### ISSUE TITLE
BUG: Unable to access super admin account page

### ISSUE THREAD

**Issue by gmai2015gm** [adamuremek/mentorship-program#70]
DESCRIPTION
When trying to access the super admin account page, the error enclosed in the screenshot appears

Steps to reproduce

Login with the admin@admin.admin credentials. 
Press the button to view your account
The error should appear

Additional Comments

Opera GX was used for testing
Please contact for any questions or demo

![Screenshot 2024-03-16 120933](https://github.com/adamuremek/mentorship-program/assets/60164202/9002e576-45e6-44c5-a1e9-a07efe576b66)

**Comment by adamuremek** [comment]
Fixed it, shouldn't allow you to view a profile now.
