### ISSUE TITLE
BUG: Get 413 Status when file too large when changing profile pic.

### ISSUE THREAD

**Issue by gmai2015gm** [adamuremek/mentorship-program#71]
_**DESCRIPTION**_
Get 413 "Request Entity Too Large" when trying to change my profile picture to a larger image.

_**STEPS TO REPRODUCE**_
1. Navigate to profile or group page (depending on whether you are mentee or mentor)
2. Click "edit page".
3. Click "change photo".
4. Select a photo that is >= 2000KB
5. The photo on the page will populate with the new photo.
6. Click "Save"
7. The 413 page will appear.

_**NOTES**_
- I don't know what the actual file size limit is. 
- Other files that are smaller (around 1000KB) work just fine.

**Comment by mdloucks** [comment]
Could you attach the image that you used? I tested a 30MB JPEG on the student profile page on dev-main and it worked fine. It might also be an encoding issue.

**Comment by adamuremek** [comment]
yeah i coudlnt get hte error to fire either, were you signed in as mentee, mentor, or admin?

**Comment by gmai2015gm** [comment]
![IMG_20180518_145413_01](https://github.com/adamuremek/mentorship-program/assets/60164202/dbc81f35-1d68-477c-b3b9-7ddd2abf1b4b)
Here's the file I was testing.

**Comment by adamuremek** [comment]
lol

**Comment by adamuremek** [comment]
I temporariily fixed this issue by increasing the Nginx payload size limit, however this is not a proper fix.
