### ISSUE TITLE
NOT A BUG: Scrolling on pages with touch/touchpad creates rubber band effect with main screen

### ISSUE THREAD

**Issue by adamuremek** [adamuremek/mentorship-program#73]
# Description
Whenever I scroll on a page on mobile or on macOS (SPECIFICALLY with a magic touchpad), the page is not locked and it "overscrolls". If i had to guess this is an Apple device related problem but it could affect other mobile devices as well.

# Steps to Reproduce
1. Open any page, preferably a scrollable one like the dashboard
2. Scroll past the normal limit (drag the screen on mobile or two finger scroll on touchpads)

Visual Demonstration:

https://github.com/adamuremek/mentorship-program/assets/25212930/d04b26d8-cd87-4e71-9666-d4e436f896e0

**Comment by mdloucks** [comment]
That being said, I found a fix for it if you want it changed @adamuremek.

https://github.com/adamuremek/mentorship-program/assets/19471665/b09cb8e3-46f1-4663-965b-b9fc2f25d87e
