### ISSUE TITLE
Handle duplicate email signup

### ISSUE THREAD

**Issue by mdloucks** [adamuremek/mentorship-program#79]
Right now, when you attempt to sign up as a mentee with an email that already exists, it boots you to this page. We should probably handle this in some way. Here's a couple ideas:

- Check email availability while they type it into the form and deny if exists.
- Redirect them to login page, and notify them somehow that their account already exists

![Screenshot 2024-03-24 at 3 01 12 PM](https://github.com/adamuremek/mentorship-program/assets/19471665/ed2dde5b-a8b6-4f5a-872a-21065c5385c8)

**Comment by Punkster81** [comment]
pretty sure done with it
![image](https://github.com/adamuremek/mentorship-program/assets/67660047/4d04c243-ef1f-40d1-ba10-19a662012537)
![image](https://github.com/adamuremek/mentorship-program/assets/67660047/aed309e6-9cde-48f8-b95c-c921ee104c7e)
