### ISSUE TITLE
BUG: The max mentee's counter changes when met

### ISSUE THREAD

**Issue by gmai2015gm** [adamuremek/mentorship-program#82]
_**DESCRIPTION**_
In this case, the mentor's profile has a max mentee count of 3. After accepting 3 mentees, have been accepted the max mentees count is changed to 9.

_**STEPS TO REPRODUCE**_
1. Sign into a verified mentor account
2. Set max mentees to 3
3. Sign in to 4 different mentee accounts. 
4. In each account, request a mentorship from your mentor account. 
5. Go back to your mentor account and accept 3 of the 4 requests. 
6. Observe that the max mentees has changed from 3 to 9 (the max)

_**Screen Capture**_
https://svsu0-my.sharepoint.com/:v:/g/personal/gamai_svsu_edu/EV27htzHMb9FjevQ9GU1loIBoclJcFBIFO4Dyw-IZWlBFQ?e=i98sGh

**Comment by gmai2015gm** [comment]
Upon further testing, the mentor still disappears from the mentor pool, they can't get any more requests, and cannot accept already existing requests (so I couldn't bring on a fourth mentee). So it looks like it's just in how that number is displayed.

**Comment by Punkster81** [comment]
Pretty sure fixed?
