### ISSUE TITLE
Multiple Mentor Requests

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#89]
A mentee is allowed to request multiple mentors at a time, but are only in the group of the most recently accepted mentor. Maybe it should only allow for one request at a time with the ability to withdraw a request? Also, when a mentee is already in a mentor's group, maybe they should have to remove themselves from the group before requesting a different mentor?
![Multiple Mentor Requests](https://github.com/adamuremek/mentorship-program/assets/148512356/9f85650b-c0c4-473d-a008-61f417b12d48)

**Comment by Mequam** [comment]
mentees can now only make requests if they are not already in a mentorship, both the dashboard UI and back end will prevent the request from being made :). 

Also updated the default page for mentees to aim to the mentee group when they are in a mentorship.

I think we probably want the mentees to be able to make more than one request though, that way they can get the best mentor from that set of requests unless someone strongly disagrees with me im closing for the time bieng :)
