### ISSUE TITLE
PFP Missing on Mobile

### ISSUE THREAD

**Issue by sajohn10** [adamuremek/mentorship-program#91]
I could not get this specific mentee PFP to display on my phone. I tried with other mentees/mentors and it showed fine. I also tried using a different image on the same profile of the same file type and it was fine. This was persistent across multiple browsers.
![Missing PFP](https://github.com/adamuremek/mentorship-program/assets/148512356/e6f764ad-d2dc-4e79-bf76-fa4cf6b2decd)
![PFP on Desktop](https://github.com/adamuremek/mentorship-program/assets/148512356/dbb3b5a4-9171-4958-9ba0-d233d5af9520)

**Comment by TheSlimyOne** [comment]
Does the bug still happen? I dont see any issues on my phone.

**Comment by sajohn10** [comment]
Looks good now 👌
